package org.hypixelskyblockmods.storagelens.config

// GLFW codes saved before Minecraft switched to SDL.
object LegacyKeyNames {
    fun name(code: Int): String {
        val name = when (code) {
            in 48..57 -> (code - 48).toString()
            in 65..90 -> ('a'.code + code - 65).toChar().toString()
            in 290..313 -> "f${code - 289}"
            in 320..329 -> "keypad.${code - 320}"
            32 -> "space"
            39 -> "apostrophe"
            44 -> "comma"
            45 -> "minus"
            46 -> "period"
            47 -> "slash"
            59 -> "semicolon"
            61 -> "equal"
            91 -> "left.bracket"
            92 -> "backslash"
            93 -> "right.bracket"
            96 -> "grave.accent"
            256 -> "escape"
            257 -> "enter"
            258 -> "tab"
            259 -> "backspace"
            260 -> "insert"
            261 -> "delete"
            262 -> "right"
            263 -> "left"
            264 -> "down"
            265 -> "up"
            266 -> "page.up"
            267 -> "page.down"
            268 -> "home"
            269 -> "end"
            280 -> "caps.lock"
            281 -> "scroll.lock"
            282 -> "num.lock"
            283 -> "print.screen"
            284 -> "pause"
            330 -> "keypad.period"
            331 -> "keypad.divide"
            332 -> "keypad.multiply"
            333 -> "keypad.subtract"
            334 -> "keypad.add"
            335 -> "keypad.enter"
            336 -> "keypad.equal"
            340 -> "left.shift"
            341 -> "left.control"
            342 -> "left.alt"
            343 -> "left.win"
            344 -> "right.shift"
            345 -> "right.control"
            346 -> "right.alt"
            347 -> "right.win"
            348 -> "menu"
            0 -> return "key.mouse.left"
            1 -> return "key.mouse.right"
            2 -> return "key.mouse.middle"
            in 3..9 -> return "key.mouse.${code + 1}"
            else -> "unknown"
        }
        return "key.keyboard.$name"
    }
}
